pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Setup Python Environment') {
            steps {
                script {
                    bat 'python -m venv venv'
                    bat 'venv\\Scripts\\pip install -r requirements.txt'
                }
            }
        }

        stage('Run Pytest & Measure Time') {
            steps {
                script {

                    def startTime = System.currentTimeMillis()

                    try {
                        def testOutput = bat(
                            script: 'venv\\Scripts\\pytest -v',
                            returnStdout: true
                        ).trim()

                        echo testOutput
                        env.TEST_STATUS = "PASSED"
                        env.TEST_LOG = testOutput

                    } catch (err) {

                        env.TEST_STATUS = "FAILED"
                        env.TEST_LOG = err.getMessage()
                    }

                    def endTime = System.currentTimeMillis()
                    def buildDuration = (endTime - startTime) / 1000

                    echo "Build Duration (seconds): ${buildDuration}"
                    env.BUILD_DURATION = buildDuration.toString()
                }
            }
        }

        stage('Evaluate Intelligence Engine') {
            steps {
                script {

                    def metricsJson = """
                    {
                        "metrics": {
                            "cpu": 50,
                            "memory": 50,
                            "disk": 40,
                            "build_time": ${env.BUILD_DURATION}
                        },
                        "test_status": "${env.TEST_STATUS}",
                        "log_text": ${groovy.json.JsonOutput.toJson(env.TEST_LOG)}
                    }
                    """

                    def response = httpRequest(
                        httpMode: 'POST',
                        contentType: 'APPLICATION_JSON',
                        requestBody: metricsJson,
                        url: 'http://localhost:5000/api/evaluate'
                    )

                    def result = readJSON text: response.content

                    echo "Decision: ${result.decision}"
                    echo "Waste Score: ${result.waste_score}"

                    if (result.decision == "BLOCK") {
                        error("Deployment Blocked by Decision Engine")
                    }
                }
            }
        }

        stage('Deploy') {
            when {
                expression { return env.TEST_STATUS == "PASSED" }
            }
            steps {
                echo "Deploying application..."
            }
        }
    }
}